# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\saans\AppData\Local\Programs\Python\Python310\Lib\site-packages\qt5_applications\Qt\bin\Warning_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Warning_Dialog(object):
    def setupUi(self, Warning_Dialog):
        Warning_Dialog.setObjectName("Warning_Dialog")
        Warning_Dialog.resize(394, 151)
        self.buttonBox = QtWidgets.QDialogButtonBox(Warning_Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 100, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Warning_Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Warning_Dialog)
        self.buttonBox.accepted.connect(Warning_Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Warning_Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Warning_Dialog)

    def retranslateUi(self, Warning_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Warning_Dialog.setWindowTitle(_translate("Warning_Dialog", "Dialog"))
        self.label.setText(_translate("Warning_Dialog", "Are sure to exit without saving?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Warning_Dialog = QtWidgets.QDialog()
    ui = Ui_Warning_Dialog()
    ui.setupUi(Warning_Dialog)
    Warning_Dialog.show()
    sys.exit(app.exec_())
